### PR TITLE
Create a rules_sass BUILD file generator

### PR DESCRIPTION
**Pull request by achew22**
This change uses Gazelle (https://github.com/bazelbuild/bazel-gazelle),
a BUILD file generator for Bazel projects, to generate rules_sass BUILD
files automatically based on the directory structure of a preexisting
project. Gazelle recently added support for plugins and I wanted to try
writing a new plugin for it.

Gazelle intelligently manages your BUILD files. It doesn't delete any
rules (unless it is appropriate to delete it), operates off of a cache,
and is fast enough to be used by the Kubernetes project for managing
their BUILD files.

Why should this be in the rules_sass repo?

Great question! I believe this should live in the rules_sass repo so
that the generator of BUILD files and the macros/rules in the repo can
be iterated on in lock step. This will help prevent circumstances where
a user of rules_sass forgets to update their dependency on Gazelle and
ends up generating garbage BUILD files that are only logically to a
former state of the rules_sass project.

How to use this:

1.  Follow the instructions on the Gazelle website for configuring
    Gazelle.
2.  In the `BUILD` file in the root of your directory, amend the
    list of installed languages to additionally include the target,
    which is created in this commit,
    "@io_bazel_rules_sass//gazelle:go_default_library",
3.  `cd` into the directory you would like to generate BUILD files for
4.  `bazel run //:gazelle`
5.  Enjoy your new BUILD files.

### CODE REVIEW

**Comment by achew22** [comment]
@jayconrod, FYI this is probably the first Gazelle plugin that isn't written by you. :tada:

Things that have to be done before this PR can be merged:

- [ ] Relative import paths almost certainly don't work. I technically didn't try, but I don't think so.
- [ ] Right now I hard code visibility to public on libraries generated from files that start with `_`, it would be better to:
    1.   If the user has explicitly set the value before, prefer that.
    1.   Read the package default_visibility and defer to that.

Things I would like guidance on:

 - [ ] In the examples you show creating an aggregator `sass_library` that includes `_fonts.scss` and `_colors.scss`, is that the way you *want* things to work or the way that is most ergonomic for hand written `BUILD` files? I assume that it was done that way for developer convenience, but I would like to hear your thoughts.

**Comment by achew22** [comment]
@nex3, that sounds like a great place to open. Thanks for taking a look!

I expect this BUILD file generator is *extremely* naive at this point, but the only way I know how to improve it is to expose it to more realistic data. I iterated on this until the very small project that I have that uses rules_sass worked but don't have a larger corpus to operate off of to improve things. I, for example, didn't even know that you could do plain-CSS imports. I'll go look that up.

Do have have other examples of places where you think it falls over? Are there specific cases you have in mind that you would like to see exercised? Do you have any larger repos I could use as a testcase?

**Comment by achew22** [comment]
@nex3, WRT correctly parsing `@import` statements. I looked around online for an EBNF/PEG that describes the language. Based on your github self description, it sounds like you might be someone eminently qualified to point me to one if it exists. I'm also happy to extract one out of a lexer/parser if you have one that you think implements the spec particularly well.

**Comment by nex3** [comment]
The grammar for Sass is quite irregular, so there isn't any formal description of it. You can find an informal description of all the Sass constructs in [the reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html), and you can look at [Dart Sass's parser](https://github.com/sass/dart-sass/blob/master/lib/src/parse/stylesheet.dart), but I think in general any thoroughly correct parser is going to need to be either fairly complex, or re-use a Sass implementation's parser.

**Comment by achew22** [comment]
Do you think I need to implement a full parser of SASS or can I get away with detecting just the import statements? I'm not trying to write a SASS compiler, you've already got that down. I'm just trying to find the things a `.sass` file depends upon. Does SASS has a concept of non-imported use (Java's fully qualified usage is an example of this and it probably has a nice technical term but I don't know it off hand. Ex: `public java.util.Date myFunction() {`). Maybe you could point me to some of the specific edge cases you have in mind that are going to require a complete parser to generate the set of dependencies. Non-imported use is the only one I can think of. I would like to learn more about SASS as a language, but my ability to hold a 3000 line lexer/parser in my head is somewhat limited.

Additionally as a high level discussion, I think it is worth setting expectations on BUILD file generators in general. My goal is to have it work in the 99% case, but 100% correctness without modifying the source is not an outcome I expect. That is to say, "this will probably work for you, but if you're doing super clever stuff with your code you might have to either manually annotate your `.sass` file to provide additional context or manually annotate the `BUILD` file to tell it how to interpret something (Gazelle already supports directives to allow this). There are going to be diabolical cases where people do strange stuff that it is probably not going to work. I don't know if it is possible in SASS but I could imagine that SASS allows you to use variables in imports, and that variables could be set by environment variables. If something like that's the case then I don't think even a comprehensive parser is going to be able to understand.

Can you help me understand what the bar you would be willing to accept this contribution is at? At one end of the spectrum is a regexp that finds imports and the other end is writing a parser/lexer for SASS. Do you have thoughts on where the acceptance mark is?

**Comment by nex3** [comment]
Part of the equation here is that we *could* have a 100% compatible parser by simply re-using the Dart implementation. So one question we need to answer is, do we get enough benefit from using Go that it's worth building a custom parser that's bound to have some failure cases and may struggle to keep up with new Sass syntax?

If we do roll a new parser in Go, I think it's crucial that it gracefully handle at least plain-CSS imports, commented-out imports, and strings that contain `@import` (or `//`, `/*`, etc). Handling `@import` in a custom property value would be good too, but I don't think it's a blocker. This could *probably* be done with just a lexer that's aware of string and comment syntax, and of course the `@import` construct, but is otherwise fairly simple.

@jelbourn @hterkelsen What do you two think?

**Comment by achew22** [comment]
> Part of the equation here is that we could have a 100% compatible parser by simply re-using the Dart implementation. So one question we need to answer is, do we get enough benefit from using Go that it's worth building a custom parser that's bound to have some failure cases and may struggle to keep up with new Sass syntax?

To me, the benefit is that Buildifer et al are all written in Go. If you want to generate BUILD files without destroying any preexisting content that is in there you would have to write a BUILD file parser and write the logic around merging attributes, detecting which targets you wish to modify, etc. I've been spelunking in the [`gazelle`](https://github.com/bazelbuild/bazel-gazelle) code and it doesn't strike me as being something fun to write. And that would have to be on top of something that symbolically held the definitions of your BUILD files. Even the [Java folk](https://github.com/bazelbuild/tools_jvm_autodeps), who presumably have access to the "one true BUILD file parser" since Bazel is in Java, opted to use the Buildifer based rule code to actually manipulate the BUILD files rather than write a new one in a new language.

It might be possible for split the baby, but I don't know enough about the dart VM (is it V8 based?) in order to answer even the most basic questions about that. It might be possible to invoke the SASS compiler against that file and emit a proto to stdout that is the parsed result of the dart parser in a reduced form. 

```proto
message ParseSourceFilesRequest {
  repeated ParseSourceFileRequest requests = 1;
}

message ParseSourceFileRequest {
  string filename = 1;
}

message ParseSourceFilesResponse {
  repeated ParseSourceFileResponse responses = 1;
}

message ParseSourceFileResponse {
  string filename = 1;

  // List of imports extracted from the 
  repeated string imports = 2;

  // Potential other metadata that someone would care about but
  // I can't think of examples at this instant.
}
```

This would be a BIG divergence from the way gazelle works right now and I don't know how @jayconrod would want to handle that. It seems like another possible migration strategy but will likely suffer from latency issues from vm startup, cold cache, compiling dart to intermediate instructions. The nice thing about regexps is that, with RE2 (the regexp engine in Go) at least, you end up with an upper bound on the number of cycles that can be spent parsing. I would be interested to hear what @jayconrod thinks. It's definitely an objective to reuse any code if possible (for accuracy), but as I stated earlier in the thread there may be a performance/accuracy tradeoff that is worth investigating.

> If we do roll a new parser in Go, I think it's crucial that it gracefully handle at least plain-CSS imports, commented-out imports, and strings that contain @import (or //, /*, etc). Handling @import in a custom property value would be good too, but I don't think it's a blocker. This could probably be done with just a lexer that's aware of string and comment syntax, and of course the @import construct, but is otherwise fairly simple.

These are definitely things I can address. Thank you for enumerating some of your concerns. I don't expect that to be an exhaustive list, but it gives me something to work off of. It seems to me that those should be very possible to handle. The one that stands out to me is handling `/*` properly. I'm going to have to think about how to handle that. I don't think it is possible in a strict regexp, but it should be possible in a PDA or a similar class of automata. Time to bust out my language theory textbooks!

**Comment by jelbourn** [comment]
In terms of the language choice, on the Angular team the decision point was basically:
* Dart has the full Sass parser, so it would give the best information from the sources. However, the Dart bazel rules are not officially supported.
* Go has the direct buildifier API and great bazel support. Parsing would be ad hoc. 

I'd agree that putting in a low amount of effort to get the majority of use cases is the most efficient use of time in the short run, and that it seems like you could reasonably get the majority of use-cases with a simplified approach in Go.

**Comment by achew22** [comment]
First, appologies for being so delinquent on my responses. The holidays were very busy.

@nex3, do you have a lexer/parser you would prefer I use for this or a pointer to a source of truth document on how to parse SASS? I know you said that the dart parser is cannon, but parsing the nearly 3500 lines of code there and converting it into something more manageable is going to take me a very long time.

**Comment by nex3** [comment]
@achew22 You can use the railroad diagrams for multiline `/* */`-style comments, strings, and URLs from [the CSS spec](https://drafts.csswg.org/css-syntax-3/#token-diagrams), with the caveat that strings and URLs can contain interpolation, which starts with (unescaped) `#{`, followed by an arbitrary series of tokens other than an unbalanced `}`, followed by `}`. Sass also supports single-line comments, which begin with `//` and last until the next newline (as defined in the spec). You can distinguish plain CSS imports using [the rules listed here](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import).

That should get you a pretty solid SCSS parser. For the indented syntax, you can ignore strings and URLs since real `@import`s always appear at the beginning of the line (after whitespace), but you'll need to be able to ignore `@import`s in [nested comments](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#Comments). This should be as simple as ignoring any lines indented deeper than a line that starts with `/*` or `//`.

**Comment by alexeagle** [comment]
hey @achew22 any update on the go parser implementation?

**Comment by achew22** [comment]
@alexeagle, no real progress on it. I looked at the railroad diagram that @nex3 linked to, thanks so much for sharing that BTW. It appears to be a token railroad diagram and not a parser diagram. It's definitely useful but it leaves a lot of defining to do. TBH, as I've explored the solution space, I'm becoming more and more partial to the idea of just expanding the current regex to handle comments correctly and seeing how it works. I don't have access to any large repositories of sass code, except ones that I wrote (and are better described as trivial examples rather than real styling) and I would be interested in seeing how well regexes handle a nontrivial set of inputs. I think writing a proper error handing lexer/parser is going to be both more complex and correctly handle a smaller set of inputs at least until some serious effort goes into making it work perfectly.

**Comment by nex3** [comment]
> It appears to be a token railroad diagram and not a parser diagram.

I'm not sure what the difference is, as long as you consume the input as just a stream of tokens (which should be sufficient for parsing imports).

**Comment by nex3** [comment]
Your example isn't valid Sass syntax at all. The only place the token `@import` can appear that's valid Sass (and CSS) is as an actual `@import` rule, or as the contents of a custom property, which is unlikely enough that we can ignore it.

**Comment by alexeagle** [comment]
replaced by #75

**Pull request closed without merging**
