### PR TITLE
Make the default output match the documented behavior

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Comment by jelbourn** [comment]
Looks like there are some CI failures

**Comment by nex3** [comment]
I still don't have access to the CI :disappointed:.

**Comment by jelbourn** [comment]
```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --keep_going --jobs=32 --build_event_json_file=/tmp/tmpaubqz294/build_bep.json --experimental_build_event_json_file_path_conversion=false --announce_rc --sandbox_tmpfs_path=/tmp --experimental_multi_threaded_digest --google_default_credentials --experimental_guard_against_concurrent_changes --remote_timeout=10 --disk_cache= --remote_max_connections=200 --experimental_remote_platform_override=properties:{name:"platform" value:"ubuntu1404"} --remote_http_cache=https://storage.googleapis.com/bazel-buildkite-cache ...
--
  | INFO: Options provided by the client:
  | Inherited 'common' options: --isatty=1 --terminal_columns=0
  | INFO: Reading rc options for 'build' from /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-g0s7-1/bazel/rules-sass/tools/bazel.rc:
  | 'build' options: --incompatible_disallow_old_style_args_add
  | ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-g0s7-1/bazel/rules-sass/sass/sass.bzl:144:27: syntax error at 'newline': expected :
  | ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-g0s7-1/bazel/rules-sass/sass/sass.bzl:149:1: syntax error at 'outdent': expected expression
  | ERROR: error loading package 'examples/nested': Extension 'sass/sass.bzl' has errors
  | ERROR: error loading package 'examples/shared': Extension 'sass/sass.bzl' has errors
  | ERROR: error loading package 'examples/hello_world': Extension 'sass/sass.bzl' has errors
  | ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-g0s7-1/bazel/rules-sass/sass/test/BUILD:3:1: error loading package 'examples/nested': Extension 'sass/sass.bzl' has errors and referenced by '//sass/test:nested_rule_test'
  | ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-g0s7-1/bazel/rules-sass/sass/test/BUILD:3:1: error loading package 'examples/hello_world': Extension 'sass/sass.bzl' has errors and referenced by '//sass/test:hello_world_rule_test'
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d3b0c17f6dbb51b8f02816ad67c64d1e/external/io_bazel_rules_sass/sass/sass.bzl:144:27: syntax error at 'newline': expected :
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d3b0c17f6dbb51b8f02816ad67c64d1e/external/io_bazel_rules_sass/sass/sass.bzl:149:1: syntax error at 'outdent': expected expression
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d3b0c17f6dbb51b8f02816ad67c64d1e/external/io_bazel_skydoc/skydoc/BUILD:84:1: error loading package '@io_bazel_skydoc//skydoc/sass': Extension 'sass/sass.bzl' has errors and referenced by '@io_bazel_skydoc//skydoc:skydoc'
  | WARNING: errors encountered while analyzing target '//sass/test:hello_world_rule_test': it will not be built
  | WARNING: errors encountered while analyzing target '//sass/test:nested_rule_test': it will not be built
  | WARNING: errors encountered while analyzing target '//sass/docs:docs': it will not be built
  | INFO: Analysis succeeded for only 2 of 5 top-level targets
  | INFO: Analysed 5 targets (34 packages loaded).
  | INFO: Found 2 targets...
  | ERROR: command succeeded, but there were loading phase errors
  | INFO: Elapsed time: 7.031s, Critical Path: 0.09s
  | INFO: 0 processes.
  | FAILED: Build did NOT complete successfully
  | At least one test failed or was flaky.
  | 🚨 Error: The command exited with status 1

```

**Comment by jelbourn** [comment]
```
WARNING: Option 'bes_best_effort' is deprecated: BES best effort upload has been removed. The flag has no more functionality attached to it and will be removed in a future release.
INFO: Streaming Build Event Protocol to buildeventservice.googleapis.com build_request_id: 5f810780-08af-4b97-9556-b5c51bd05de5 invocation_id: 16a6f79f-f211-413f-9158-89a43a892304
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=0
INFO: Reading rc options for 'build' from /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/tools/bazel.rc:
  'build' options: --incompatible_disallow_old_style_args_add
Loading:
Loading: 0 packages loaded
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/examples/hello_world/BUILD:6:1: In rule //examples/hello_world:hello_world: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/sass/sass.bzl", line 132
		_strip_extension(src)
	File "/var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/sass/sass.bzl", line 146, in _strip_extension
		path.split(".")
type 'Label' has no method split(string)
Loading: 4 packages loaded
    currently loading: sass/test ... (2 packages)
ERROR: package contains errors: examples/hello_world
Loading: 4 packages loaded
    currently loading: sass/test ... (2 packages)
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/examples/nested/BUILD:6:1: In rule //examples/nested:nested: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/sass/sass.bzl", line 132
		_strip_extension(src)
	File "/var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/sass/sass.bzl", line 146, in _strip_extension
		path.split(".")
type 'Label' has no method split(string)
Loading: 5 packages loaded
    currently loading: sass/test
ERROR: package contains errors: examples/nested
Loading: 5 packages loaded
    currently loading: sass/test
WARNING: Target pattern parsing failed.
Loading: 6 packages loaded
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/864cc561c028e41b5463c18c76da5ae7/external/io_bazel_skydoc/skydoc/sass/BUILD:7:1: In rule @io_bazel_skydoc//skydoc/sass:main: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/864cc561c028e41b5463c18c76da5ae7/external/io_bazel_rules_sass/sass/sass.bzl", line 132
		_strip_extension(src)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/864cc561c028e41b5463c18c76da5ae7/external/io_bazel_rules_sass/sass/sass.bzl", line 146, in _strip_extension
		path.split(".")
type 'Label' has no method split(string)
Analyzing: 11 targets (22 packages loaded)
    currently loading: @protobuf//
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/864cc561c028e41b5463c18c76da5ae7/external/io_bazel_skydoc/skydoc/BUILD:84:1: no such target '@io_bazel_skydoc//skydoc/sass:main.css': target 'main.css' not declared in package 'skydoc/sass' (did you mean 'main.scss'?) defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/864cc561c028e41b5463c18c76da5ae7/external/io_bazel_skydoc/skydoc/sass/BUILD and referenced by '@io_bazel_skydoc//skydoc:skydoc'
Analyzing: 11 targets (35 packages loaded)
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/examples/hello_world/BUILD:6:1: Target '//examples/hello_world:main.scss' contains an error and its package is in error and referenced by '//examples/hello_world:hello_world'
Analyzing: 11 targets (37 packages loaded)
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/examples/hello_world/BUILD:14:1: Target '//examples/hello_world:main.scss' contains an error and its package is in error and referenced by '//examples/hello_world:hello_world_no_sourcemap'
Analyzing: 11 targets (37 packages loaded)
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/examples/nested/BUILD:6:1: Target '//examples/nested:dir/main.scss' contains an error and its package is in error and referenced by '//examples/nested:nested'
Analyzing: 11 targets (37 packages loaded)
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/sass/test/BUILD:3:1: Target '//examples/hello_world:hello_world' contains an error and its package is in error and referenced by '//sass/test:hello_world_rule_test'
Analyzing: 11 targets (38 packages loaded)
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-vx50-1/bazel/rules-sass/sass/test/BUILD:3:1: Target '//examples/nested:nested' contains an error and its package is in error and referenced by '//sass/test:nested_rule_test'
Analyzing: 11 targets (38 packages loaded)
WARNING: errors encountered while analyzing target '//sass/test:hello_world_rule_test': it will not be built
Analyzing: 11 targets (38 packages loaded)
WARNING: errors encountered while analyzing target '//examples/nested:nested': it will not be built
Analyzing: 11 targets (38 packages loaded)
WARNING: errors encountered while analyzing target '//examples/hello_world:hello_world_no_sourcemap': it will not be built
Analyzing: 11 targets (38 packages loaded)
WARNING: errors encountered while analyzing target '//examples/hello_world:hello_world': it will not be built
Analyzing: 11 targets (38 packages loaded)
WARNING: errors encountered while analyzing target '//sass/docs:docs': it will not be built
Analyzing: 11 targets (38 packages loaded)
WARNING: errors encountered while analyzing target '//sass/test:nested_rule_test': it will not be built
Analyzing: 11 targets (38 packages loaded)
INFO: Analysis succeeded for only 5 of 11 top-level targets
Analyzing: 11 targets (38 packages loaded)
INFO: Analysed 11 targets (38 packages loaded).
Building: no action
INFO: Found 5 targets...
Building: no action
[0 / 4] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but there were errors parsing the target pattern
[8 / 8] no action
INFO: Elapsed time: 6.961s, Critical Path: 0.06s
[8 / 8] no action
INFO: 0 processes.
[8 / 8] no action
FAILED: Build did NOT complete successfully
```

**Pull request merged**
