### PR TITLE
Wire the "--embed-sources" flag through Sass bazel rules.

### PR DESCRIPTION
**Pull request by ju1i3nm**
--embed-sources embeds source file contents in source maps.

### CODE REVIEW

**Comment by ju1i3nm** [comment]
Done.

**Comment by nex3** [comment]
It looks like the Windows tests are failing because of https://github.com/bazelbuild/bazel/issues/6122, but I don't remember how we worked around that before and I can't figure out why whatever workaround we used doesn't apply here. @jelbourn or @alexeagle, do you have any insight?

**Comment by ju1i3nm** [comment]
I think I found the workaround, PTAL.

**Comment by nex3** [comment]
Thanks!

**Pull request merged**
