### PR TITLE
update @io_bazel_rules_go//go:def.bzl for https://github.com/bazelbui…

### PR DESCRIPTION
**Pull request by aranguyen**
…ld/continuous-integration/issues/1404

### CODE REVIEW

**Review by davidzchen — APPROVED** [review]

**Review by davidzchen — CHANGES_REQUESTED** [review]
Actually, there seems to be an issue with rules_go:

```
ERROR: error loading package '': Every .bzl file must have a corresponding package, but '@io_bazel_rules_go//go:def.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
--
  | Traceback (most recent call last):
  | File "bazelci.py", line 3655, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 3635, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 1285, in execute_commands
  | bazel_version = print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 1539, in print_bazel_version_info
  | + ["--nosystem_rc", "--nohome_rc", "info"]
  | File "bazelci.py", line 2281, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['bazel', '--nosystem_rc', '--nohome_rc', 'info']' returned non-zero exit status 1.
  | 🚨 Error: The command exited with status 1
```

**Comment by aranguyen** [comment]
@davidzchen it should be good now. I updated `rules_go` to `0.34.0` which is the latest.

**Comment by Wyverald** [comment]
Gentle ping. This project remains broken on Bazel CI -- we'll need to disable it on Bazel CI if this isn't resolved soon.

**Comment by mai93** [comment]
@davidzchen can we merge this PR as the project is still broken on Bazel CI?

**Comment by davidzchen** [comment]
Merged. Sorry for the delay. Thank you for your contribution!

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1256#01834061-1a6a-4eed-809f-baf9ffe881f3

Still failing with 
```
(09:14:05) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/aa0b9b1de98002d7e3bc86da56680205/external/bazel_tools/platforms/BUILD:39:6: in alias rule @bazel_tools//platforms:s390x: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
(09:14:05) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/aa0b9b1de98002d7e3bc86da56680205/external/bazel_tools/platforms/BUILD:39:6: Analysis of target '@bazel_tools//platforms:s390x' failed
(09:14:05) ERROR: /var/lib/buildkite-agent/builds/bk-docker-p824/bazel-downstream-projects/rules_sass/sass/BUILD:12:14: While resolving toolchains for target //sass:sass: invalid registered toolchain '@go_sdk//:go_linux_s390x':
```

**Comment by meteorcloudy** [comment]
You probably need to update the rules_nodejs version due to https://github.com/bazelbuild/rules_nodejs/pull/2536

**Comment by meteorcloudy** [comment]
Oh, I see, it's because downstream was testing rules_sass at an old commit because our main build was scheduled to run with "master" branch, which caused the "last green commit" not to be updated for rules_sasa. Fixed now!

**Pull request merged**
